import { ADDRESS_FIELD_ERROR_PATTERN, CITY_ADDRESS_LABEL, EMAIL_LABEL, PHONE_FIELD_ERROR_PATTERN, PHONE_LABEL, POSTAL_ADDRESS_LABEL, POSTAL_FIELD_ERROR_PATTERN, SHOPNAME_LABEL, SHOPOWNER_NAME_LABEL, STREET_ADDRESS_LABEL } from '../../constants/strings';
import { TextInputProps } from '../common/forms/TextInput/TextInput';

export const shopFormFields: (Omit<TextInputProps, 'register' | 'trigger'> & {key: string})[] = [
  {
    key: '1',
    name: 'shopName',
    type: 'text',
    label: SHOPNAME_LABEL,
    minLength: 3,
    maxLength: 100,
    isRequired: true,
  },
  {
    key: '2',
    name: 'shopOwnerName',
    type: 'text',
    label: SHOPOWNER_NAME_LABEL,
    minLength: 3,
    maxLength: 50,
    isRequired: true,
  },
  {
    key: '3',
    name: 'email',
    type: 'email',
    label: EMAIL_LABEL,
    patternExp: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.(com|net)$/,
    isRequired: true,
  },
  {
    key: '4',
    name: 'phone',
    type: 'tel',
    label: PHONE_LABEL,
    patternExp: /^[0-9]{6,12}$/,
    patternError: PHONE_FIELD_ERROR_PATTERN,
    isRequired: true,
  },
  {
    key: '5',
    name: 'address',
    type: 'text',
    label: STREET_ADDRESS_LABEL,
    minLength: 6,
    maxLength: 100,
    patternExp: /^[a-zA-Z0-9\s,'-]*$/,
    patternError: ADDRESS_FIELD_ERROR_PATTERN,
    isRequired: true,
  },
  {
    key: '6',
    name: 'city',
    type: 'text',
    label: CITY_ADDRESS_LABEL,
    minLength: 2,
    maxLength: 50,
    isRequired: true,
  },
  {
    key: '7',
    name: 'postal',
    type: 'text',
    label: POSTAL_ADDRESS_LABEL,
    patternExp: /^[A-Za-z0-9\s-]{3,10}$/,
    patternError: POSTAL_FIELD_ERROR_PATTERN,
    isRequired: true,
  },
]
